### ISSUE TITLE
add a new collaborator

### ISSUE THREAD

**Issue by hparfr** [OCA/module-composition-analysis#73]
Hi @sebalix 

Can you please add https://github.com/paradoxxxzero to this repo ?
He has started to port our pr scan from gh api to this modules.
 
Thanks

**Comment by sebalix** [comment]
Hello @hparfr, I tried but we are lacking of available seat on GitHub.

I can add him to my fork if it helps, but that's not the best...

EDIT: that's the price to keep this repo private, maybe we should start thinking about putting this public again, that needs to be discussed internally

**Comment by hparfr** [comment]
you can remove seb may be :)

**Comment by sebalix** [comment]
Sadly Sebastien Beau is not part of the collaborators of this repository (and I don't know where to check if he still takes a seat in C2C org)

**Comment by sebalix** [comment]
@hparfr @paradoxxxzero your account has now access to the repository, thanks to @gurneyalex
